---

- hosts: linux-workstation
  become: true

  tasks:
    - set_fact:
        package_url: https://dl.google.com/linux/direct/google-talkplugin_current_x86_64.rpm
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'openSUSE'
    - set_fact: 
        package_url: name=https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - package: name={{ package_url }}
