---

- hosts: linux-workstation
  become: false

  vars:
    firefox:
      addons:
        - url: https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2
        - url: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin
        - url: https://addons.mozilla.org/en-US/firefox/addon/jsonview
      prefs:
        - name: mousewheel.default.delta_multiplier_y
          value: 200
        - name: signon.rememberSignons
          value: false

  roles:
    - alzadude.firefox
